const commonLanguageOrder = ['english', 'spanish', 'french', 'german', 'japanese'];

const languageNames = [
	'English',
	'Spanish',
	'French',
	'German',
	'Japanese',
	'Abkhazian',
	'Afar',
	'Afrikaans',
	'Akan',
	'Albanian',
	'Amharic',
	'Arabic',
	'Aragonese',
	'Armenian',
	'Assamese',
	'Avaric',
	'Avestan',
	'Aymara',
	'Azerbaijani',
	'Bambara',
	'Bashkir',
	'Basque',
	'Belarusian',
	'Bengali',
	'Bislama',
	'Bosnian',
	'Breton',
	'Bulgarian',
	'Burmese',
	'Catalan',
	'Central Khmer',
	'Chamorro',
	'Chechen',
	'Chichewa',
	'Chinese',
	'Church Slavic',
	'Chuvash',
	'Cornish',
	'Corsican',
	'Cree',
	'Croatian',
	'Czech',
	'Danish',
	'Divehi',
	'Dutch',
	'Dzongkha',
	'Esperanto',
	'Estonian',
	'Ewe',
	'Faroese',
	'Fijian',
	'Finnish',
	'Fulah',
	'Gaelic',
	'Galician',
	'Ganda',
	'Georgian',
	'Greek',
	'Guarani',
	'Gujarati',
	'Haitian',
	'Hausa',
	'Hebrew',
	'Herero',
	'Hindi',
	'Hiri Motu',
	'Hungarian',
	'Icelandic',
	'Ido',
	'Igbo',
	'Indonesian',
	'Interlingua',
	'Interlingue',
	'Inuktitut',
	'Inupiaq',
	'Irish',
	'Italian',
	'Javanese',
	'Kalaallisut',
	'Kannada',
	'Kanuri',
	'Kashmiri',
	'Kazakh',
	'Kikuyu',
	'Kinyarwanda',
	'Kirghiz',
	'Komi',
	'Kongo',
	'Khmer',
	'Korean',
	'Kuanyama',
	'Kurdish',
	'Lao',
	'Latin',
	'Latvian',
	'Limburgan',
	'Lingala',
	'Lithuanian',
	'Luba-Katanga',
	'Luxembourgish',
	'Macedonian',
	'Malagasy',
	'Malay',
	'Malayalam',
	'Maltese',
	'Manx',
	'Maori',
	'Marathi',
	'Marshallese',
	'Mongolian',
	'Nauru',
	'Navajo',
	'North Ndebele',
	'South Ndebele',
	'Ndonga',
	'Nepali',
	'Norwegian',
	'Norwegian Bokmal',
	'Norwegian Nynorsk',
	'Occitan',
	'Ojibwa',
	'Oriya',
	'Oromo',
	'Ossetian',
	'Pali',
	'Pashto',
	'Persian',
	'Polish',
	'Portuguese',
	'Punjabi',
	'Quechua',
	'Romanian',
	'Romansh',
	'Rundi',
	'Russian',
	'Samoan',
	'Sango',
	'Sanskrit',
	'Sardinian',
	'Serbian',
	'Shona',
	'Sichuan Yi',
	'Sindhi',
	'Sinhala',
	'Slovak',
	'Slovenian',
	'Somali',
	'Sotho',
	'Sundanese',
	'Swahili',
	'Swati',
	'Swedish',
	'Tagalog',
	'Tahitian',
	'Tajik',
	'Tamil',
	'Tatar',
	'Telugu',
	'Thai',
	'Tibetan',
	'Tigrinya',
	'Tonga',
	'Tsonga',
	'Tswana',
	'Turkish',
	'Turkmen',
	'Twi',
	'Ukrainian',
	'Urdu',
	'Uyghur',
	'Uzbek',
	'Venda',
	'Vietnamese',
	'Volapuk',
	'Walloon',
	'Welsh',
	'Western Frisian',
	'Wolof',
	'Xhosa',
	'Yiddish',
	'Yoruba',
	'Zhuang',
	'Zulu'
];

const languageCodes: Record<string, string> = {
	Abkhazian: 'AB',
	Afar: 'AA',
	Afrikaans: 'AF',
	Akan: 'AK',
	Albanian: 'SQ',
	Amharic: 'AM',
	Arabic: 'AR',
	Aragonese: 'AN',
	Armenian: 'HY',
	Assamese: 'AS',
	Avaric: 'AV',
	Avestan: 'AE',
	Aymara: 'AY',
	Azerbaijani: 'AZ',
	Bambara: 'BM',
	Bashkir: 'BA',
	Basque: 'EU',
	Belarusian: 'BE',
	Bengali: 'BN',
	Bislama: 'BI',
	Bosnian: 'BS',
	Breton: 'BR',
	Bulgarian: 'BG',
	Burmese: 'MY',
	Catalan: 'CA',
	'Central Khmer': 'KM',
	Chamorro: 'CH',
	Chechen: 'CE',
	Chichewa: 'NY',
	Chinese: 'ZH',
	'Church Slavic': 'CU',
	Chuvash: 'CV',
	Cornish: 'KW',
	Corsican: 'CO',
	Cree: 'CR',
	Croatian: 'HR',
	Czech: 'CS',
	Danish: 'DA',
	Divehi: 'DV',
	Dutch: 'NL',
	Dzongkha: 'DZ',
	English: 'EN',
	Esperanto: 'EO',
	Estonian: 'ET',
	Ewe: 'EE',
	Faroese: 'FO',
	Fijian: 'FJ',
	Finnish: 'FI',
	French: 'FR',
	Fulah: 'FF',
	Gaelic: 'GD',
	Galician: 'GL',
	Ganda: 'LG',
	Georgian: 'KA',
	German: 'DE',
	Greek: 'EL',
	Guarani: 'GN',
	Gujarati: 'GU',
	Haitian: 'HT',
	Hausa: 'HA',
	Hebrew: 'HE',
	Herero: 'HZ',
	Hindi: 'HI',
	'Hiri Motu': 'HO',
	Hungarian: 'HU',
	Icelandic: 'IS',
	Ido: 'IO',
	Igbo: 'IG',
	Indonesian: 'ID',
	Interlingua: 'IA',
	Interlingue: 'IE',
	Inuktitut: 'IU',
	Inupiaq: 'IK',
	Irish: 'GA',
	Italian: 'IT',
	Japanese: 'JA',
	Javanese: 'JV',
	Kalaallisut: 'KL',
	Kannada: 'KN',
	Kanuri: 'KR',
	Kashmiri: 'KS',
	Kazakh: 'KK',
	Khmer: 'KM',
	Kikuyu: 'KI',
	Kinyarwanda: 'RW',
	Kirghiz: 'KY',
	Komi: 'KV',
	Kongo: 'KG',
	Korean: 'KO',
	Kuanyama: 'KJ',
	Kurdish: 'KU',
	Lao: 'LO',
	Latin: 'LA',
	Latvian: 'LV',
	Limburgan: 'LI',
	Lingala: 'LN',
	Lithuanian: 'LT',
	'Luba-Katanga': 'LU',
	Luxembourgish: 'LB',
	Macedonian: 'MK',
	Malagasy: 'MG',
	Malay: 'MS',
	Malayalam: 'ML',
	Maltese: 'MT',
	Manx: 'GV',
	Maori: 'MI',
	Marathi: 'MR',
	Marshallese: 'MH',
	Mongolian: 'MN',
	Nauru: 'NA',
	Navajo: 'NV',
	Ndonga: 'NG',
	Nepali: 'NE',
	'North Ndebele': 'ND',
	Norwegian: 'NO',
	'Norwegian Bokmal': 'NB',
	'Norwegian Nynorsk': 'NN',
	Occitan: 'OC',
	Ojibwa: 'OJ',
	Oriya: 'OR',
	Oromo: 'OM',
	Ossetian: 'OS',
	Pali: 'PI',
	Pashto: 'PS',
	Persian: 'FA',
	Polish: 'PL',
	Portuguese: 'PT',
	Punjabi: 'PA',
	Quechua: 'QU',
	Romanian: 'RO',
	Romansh: 'RM',
	Rundi: 'RN',
	Russian: 'RU',
	Samoan: 'SM',
	Sango: 'SG',
	Sanskrit: 'SA',
	Sardinian: 'SC',
	Serbian: 'SR',
	Shona: 'SN',
	'Sichuan Yi': 'II',
	Sindhi: 'SD',
	Sinhala: 'SI',
	Slovak: 'SK',
	Slovenian: 'SL',
	Somali: 'SO',
	'South Ndebele': 'NR',
	Sotho: 'ST',
	Spanish: 'ES',
	Sundanese: 'SU',
	Swahili: 'SW',
	Swati: 'SS',
	Swedish: 'SV',
	Tagalog: 'TL',
	Tahitian: 'TY',
	Tajik: 'TG',
	Tamil: 'TA',
	Tatar: 'TT',
	Telugu: 'TE',
	Thai: 'TH',
	Tibetan: 'BO',
	Tigrinya: 'TI',
	Tonga: 'TO',
	Tsonga: 'TS',
	Tswana: 'TN',
	Turkish: 'TR',
	Turkmen: 'TK',
	Twi: 'TW',
	Ukrainian: 'UK',
	Urdu: 'UR',
	Uyghur: 'UG',
	Uzbek: 'UZ',
	Venda: 'VE',
	Vietnamese: 'VI',
	Volapuk: 'VO',
	Walloon: 'WA',
	Welsh: 'CY',
	'Western Frisian': 'FY',
	Wolof: 'WO',
	Xhosa: 'XH',
	Yiddish: 'YI',
	Yoruba: 'YO',
	Zhuang: 'ZA',
	Zulu: 'ZU'
};

export const targetLanguageOptions = languageNames
	.map((label) => ({
		id: languageId(label),
		label,
		code: languageCode(label),
		displayLabel: `${label} (${languageCode(label)})`
	}))
	.sort((left, right) => {
		const leftCommon = commonLanguageOrder.indexOf(left.id);
		const rightCommon = commonLanguageOrder.indexOf(right.id);
		if (leftCommon !== rightCommon) {
			if (leftCommon === -1) return 1;
			if (rightCommon === -1) return -1;
			return leftCommon - rightCommon;
		}
		return left.label.localeCompare(right.label);
	});

export function languageLabel(id: string) {
	return targetLanguageOptions.find((option) => option.id === id)?.label ?? id;
}

function languageId(label: string) {
	return label.toLowerCase().replace(/[^a-z0-9]+/g, '-');
}

function languageCode(label: string) {
	return languageCodes[label] ?? label.slice(0, 2).toUpperCase();
}
