package storage

import (
	storagegen "media-manager/internal/storage/generated"

	"github.com/google/uuid"
)

func indexerCreateParams(id uuid.UUID, input IndexerInput) storagegen.CreateIndexerParams {
	return storagegen.CreateIndexerParams{
		ID:                 id,
		DefinitionID:       input.DefinitionID,
		Name:               input.Name,
		Implementation:     input.Implementation,
		ImplementationName: input.ImplementationName,
		Protocol:           input.Protocol,
		Privacy:            input.Privacy,
		Language:           input.Language,
		Encoding:           textValue(input.Encoding),
		Description:        textValue(input.Description),
		IndexerUrls:        input.IndexerURLs,
		LegacyUrls:         input.LegacyURLs,
		BaseUrl:            input.BaseURL,
		ApiKey:             textValue(input.APIKey),
		Categories:         input.Categories,
		MediaTypeScopes:    input.MediaTypeScopes,
		TagScopes:          input.TagScopes,
		Fields:             input.Fields,
		Capabilities:       input.Capabilities,
		Redirect:           input.Redirect,
		AppProfileID:       input.AppProfileID,
		MinimumSeeders:     int4Value(input.MinimumSeeders),
		SeedRatio:          input.SeedRatio,
		SeedTime:           int4Value(input.SeedTime),
		PackSeedTime:       int4Value(input.PackSeedTime),
		PreferMagnetUrl:    input.PreferMagnetURL,
		SupportsRss:        input.SupportsRSS,
		SupportsSearch:     input.SupportsSearch,
		SupportsRedirect:   input.SupportsRedirect,
		SupportsPagination: input.SupportsPagination,
		Enabled:            input.Enabled,
		Priority:           input.Priority,
	}
}

func indexerUpdateParams(id uuid.UUID, input IndexerInput) storagegen.UpdateIndexerParams {
	return storagegen.UpdateIndexerParams{
		ID:                 id,
		DefinitionID:       input.DefinitionID,
		Name:               input.Name,
		Implementation:     input.Implementation,
		ImplementationName: input.ImplementationName,
		Protocol:           input.Protocol,
		Privacy:            input.Privacy,
		Language:           input.Language,
		Encoding:           textValue(input.Encoding),
		Description:        textValue(input.Description),
		IndexerUrls:        input.IndexerURLs,
		LegacyUrls:         input.LegacyURLs,
		BaseUrl:            input.BaseURL,
		ApiKey:             textValue(input.APIKey),
		Categories:         input.Categories,
		MediaTypeScopes:    input.MediaTypeScopes,
		TagScopes:          input.TagScopes,
		Fields:             input.Fields,
		Capabilities:       input.Capabilities,
		Redirect:           input.Redirect,
		AppProfileID:       input.AppProfileID,
		MinimumSeeders:     int4Value(input.MinimumSeeders),
		SeedRatio:          input.SeedRatio,
		SeedTime:           int4Value(input.SeedTime),
		PackSeedTime:       int4Value(input.PackSeedTime),
		PreferMagnetUrl:    input.PreferMagnetURL,
		SupportsRss:        input.SupportsRSS,
		SupportsSearch:     input.SupportsSearch,
		SupportsRedirect:   input.SupportsRedirect,
		SupportsPagination: input.SupportsPagination,
		Enabled:            input.Enabled,
		Priority:           input.Priority,
	}
}

func indexerFromRow(row storagegen.AppIndexer) Indexer {
	return Indexer{
		ID:                   row.ID,
		DefinitionID:         row.DefinitionID,
		Name:                 row.Name,
		Implementation:       row.Implementation,
		ImplementationName:   row.ImplementationName,
		Protocol:             row.Protocol,
		Privacy:              row.Privacy,
		Language:             row.Language,
		Encoding:             textPtr(row.Encoding),
		Description:          textPtr(row.Description),
		IndexerURLs:          row.IndexerUrls,
		LegacyURLs:           row.LegacyUrls,
		BaseURL:              row.BaseUrl,
		APIKey:               textPtr(row.ApiKey),
		Categories:           row.Categories,
		MediaTypeScopes:      row.MediaTypeScopes,
		TagScopes:            row.TagScopes,
		Fields:               row.Fields,
		Capabilities:         row.Capabilities,
		Redirect:             row.Redirect,
		AppProfileID:         row.AppProfileID,
		MinimumSeeders:       int4Ptr(row.MinimumSeeders),
		SeedRatio:            row.SeedRatio,
		SeedTime:             int4Ptr(row.SeedTime),
		PackSeedTime:         int4Ptr(row.PackSeedTime),
		PreferMagnetURL:      row.PreferMagnetUrl,
		SupportsRSS:          row.SupportsRss,
		SupportsSearch:       row.SupportsSearch,
		SupportsRedirect:     row.SupportsRedirect,
		SupportsPagination:   row.SupportsPagination,
		Enabled:              row.Enabled,
		Priority:             row.Priority,
		HealthStatus:         row.HealthStatus,
		LastQueryAt:          row.LastQueryAt,
		LastSuccessAt:        row.LastSuccessAt,
		LastFailureAt:        row.LastFailureAt,
		NextCheckAt:          row.NextCheckAt,
		LastStatusCode:       int4Ptr(row.LastStatusCode),
		LastError:            textPtr(row.LastError),
		FailureCount:         row.FailureCount,
		RSSMarkerPublishedAt: row.RssMarkerPublishedAt,
		RSSMarkerGUID:        textPtr(row.RssMarkerGuid),
		RSSMarkerDownloadURL: textPtr(row.RssMarkerDownloadUrl),
		CreatedAt:            row.CreatedAt,
		UpdatedAt:            row.UpdatedAt,
	}
}
