// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package httpapi

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	SessionCookieScopes sessionCookieContextKey = "sessionCookie.Scopes"
)

// Defines values for DownloadClientType.
const (
	Sabnzbd      DownloadClientType = "sabnzbd"
	Transmission DownloadClientType = "transmission"
)

// Valid indicates whether the value is a known member of the DownloadClientType enum.
func (e DownloadClientType) Valid() bool {
	switch e {
	case Sabnzbd:
		return true
	case Transmission:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Degraded    HealthStatus = "degraded"
	Ok          HealthStatus = "ok"
	Unavailable HealthStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Ok:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// Defines values for IndexerType.
const (
	Newznab IndexerType = "newznab"
	Rss     IndexerType = "rss"
	Torznab IndexerType = "torznab"
)

// Valid indicates whether the value is a known member of the IndexerType enum.
func (e IndexerType) Valid() bool {
	switch e {
	case Newznab:
		return true
	case Rss:
		return true
	case Torznab:
		return true
	default:
		return false
	}
}

// Defines values for ToolName.
const (
	Ffmpeg     ToolName = "ffmpeg"
	Ffprobe    ToolName = "ffprobe"
	Mediainfo  ToolName = "mediainfo"
	Mkvextract ToolName = "mkvextract"
	Mkvmerge   ToolName = "mkvmerge"
)

// Valid indicates whether the value is a known member of the ToolName enum.
func (e ToolName) Valid() bool {
	switch e {
	case Ffmpeg:
		return true
	case Ffprobe:
		return true
	case Mediainfo:
		return true
	case Mkvextract:
		return true
	case Mkvmerge:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	Admin UserRole = "admin"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case Admin:
		return true
	default:
		return false
	}
}

// DownloadClient defines model for DownloadClient.
type DownloadClient struct {
	ApiKey    *string            `json:"apiKey,omitempty"`
	BaseUrl   string             `json:"baseUrl"`
	Category  *string            `json:"category,omitempty"`
	CreatedAt time.Time          `json:"createdAt"`
	Enabled   bool               `json:"enabled"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Password  *string            `json:"password,omitempty"`
	Priority  int32              `json:"priority"`
	Type      DownloadClientType `json:"type"`
	UpdatedAt time.Time          `json:"updatedAt"`
	Username  *string            `json:"username,omitempty"`
}

// DownloadClientListResponse defines model for DownloadClientListResponse.
type DownloadClientListResponse struct {
	Clients []DownloadClient `json:"clients"`
}

// DownloadClientRequest defines model for DownloadClientRequest.
type DownloadClientRequest struct {
	ApiKey   *string            `json:"apiKey,omitempty"`
	BaseUrl  string             `json:"baseUrl"`
	Category *string            `json:"category,omitempty"`
	Enabled  bool               `json:"enabled"`
	Name     string             `json:"name"`
	Password *string            `json:"password,omitempty"`
	Priority int32              `json:"priority"`
	Type     DownloadClientType `json:"type"`
	Username *string            `json:"username,omitempty"`
}

// DownloadClientType defines model for DownloadClientType.
type DownloadClientType string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Commit  string       `json:"commit"`
	Status  HealthStatus `json:"status"`
	Time    time.Time    `json:"time"`
	Version string       `json:"version"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus string

// Indexer defines model for Indexer.
type Indexer struct {
	ApiKey     *string            `json:"apiKey,omitempty"`
	BaseUrl    string             `json:"baseUrl"`
	Categories *[]int32           `json:"categories,omitempty"`
	CreatedAt  time.Time          `json:"createdAt"`
	Enabled    bool               `json:"enabled"`
	Id         openapi_types.UUID `json:"id"`
	Name       string             `json:"name"`
	Priority   int32              `json:"priority"`
	Type       IndexerType        `json:"type"`
	UpdatedAt  time.Time          `json:"updatedAt"`
}

// IndexerListResponse defines model for IndexerListResponse.
type IndexerListResponse struct {
	Indexers []Indexer `json:"indexers"`
}

// IndexerRequest defines model for IndexerRequest.
type IndexerRequest struct {
	ApiKey     *string     `json:"apiKey,omitempty"`
	BaseUrl    string      `json:"baseUrl"`
	Categories *[]int32    `json:"categories,omitempty"`
	Enabled    bool        `json:"enabled"`
	Name       string      `json:"name"`
	Priority   int32       `json:"priority"`
	Type       IndexerType `json:"type"`
}

// IndexerType defines model for IndexerType.
type IndexerType string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// SessionResponse defines model for SessionResponse.
type SessionResponse struct {
	Authenticated bool         `json:"authenticated"`
	ExpiresAt     *time.Time   `json:"expiresAt,omitempty"`
	User          *UserSummary `json:"user,omitempty"`
}

// ToolName defines model for ToolName.
type ToolName string

// ToolStatus defines model for ToolStatus.
type ToolStatus struct {
	Available bool     `json:"available"`
	Error     *string  `json:"error,omitempty"`
	Name      ToolName `json:"name"`
	Path      *string  `json:"path,omitempty"`
	Required  bool     `json:"required"`
	Version   *string  `json:"version,omitempty"`
}

// ToolStatusResponse defines model for ToolStatusResponse.
type ToolStatusResponse struct {
	Tools []ToolStatus `json:"tools"`
}

// UserRole defines model for UserRole.
type UserRole string

// UserSummary defines model for UserSummary.
type UserSummary struct {
	Id       openapi_types.UUID `json:"id"`
	Role     UserRole           `json:"role"`
	Username string             `json:"username"`
}

// ResourceId defines model for ResourceId.
type ResourceId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// RateLimited defines model for RateLimited.
type RateLimited = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// sessionCookieContextKey is the context key for sessionCookie security scheme
type sessionCookieContextKey string

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// CreateDownloadClientJSONRequestBody defines body for CreateDownloadClient for application/json ContentType.
type CreateDownloadClientJSONRequestBody = DownloadClientRequest

// UpdateDownloadClientJSONRequestBody defines body for UpdateDownloadClient for application/json ContentType.
type UpdateDownloadClientJSONRequestBody = DownloadClientRequest

// CreateIndexerJSONRequestBody defines body for CreateIndexer for application/json ContentType.
type CreateIndexerJSONRequestBody = IndexerRequest

// UpdateIndexerJSONRequestBody defines body for UpdateIndexer for application/json ContentType.
type UpdateIndexerJSONRequestBody = IndexerRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Log in with local admin credentials
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Log out and clear the current session
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Get current session
	// (GET /auth/session)
	GetSession(w http.ResponseWriter, r *http.Request)
	// Stream server-sent application events
	// (GET /events)
	StreamEvents(w http.ResponseWriter, r *http.Request)
	// Get application health
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// List configured download clients
	// (GET /settings/download-clients)
	ListDownloadClients(w http.ResponseWriter, r *http.Request)
	// Create a download client
	// (POST /settings/download-clients)
	CreateDownloadClient(w http.ResponseWriter, r *http.Request)
	// Delete a download client
	// (DELETE /settings/download-clients/{id})
	DeleteDownloadClient(w http.ResponseWriter, r *http.Request, id ResourceId)
	// Update a download client
	// (PUT /settings/download-clients/{id})
	UpdateDownloadClient(w http.ResponseWriter, r *http.Request, id ResourceId)
	// List configured indexers
	// (GET /settings/indexers)
	ListIndexers(w http.ResponseWriter, r *http.Request)
	// Create an indexer
	// (POST /settings/indexers)
	CreateIndexer(w http.ResponseWriter, r *http.Request)
	// Delete an indexer
	// (DELETE /settings/indexers/{id})
	DeleteIndexer(w http.ResponseWriter, r *http.Request, id ResourceId)
	// Update an indexer
	// (PUT /settings/indexers/{id})
	UpdateIndexer(w http.ResponseWriter, r *http.Request, id ResourceId)
	// Get detected media tool capabilities
	// (GET /system/tools)
	GetToolStatus(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Log in with local admin credentials
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Log out and clear the current session
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current session
// (GET /auth/session)
func (_ Unimplemented) GetSession(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stream server-sent application events
// (GET /events)
func (_ Unimplemented) StreamEvents(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get application health
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List configured download clients
// (GET /settings/download-clients)
func (_ Unimplemented) ListDownloadClients(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a download client
// (POST /settings/download-clients)
func (_ Unimplemented) CreateDownloadClient(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a download client
// (DELETE /settings/download-clients/{id})
func (_ Unimplemented) DeleteDownloadClient(w http.ResponseWriter, r *http.Request, id ResourceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a download client
// (PUT /settings/download-clients/{id})
func (_ Unimplemented) UpdateDownloadClient(w http.ResponseWriter, r *http.Request, id ResourceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List configured indexers
// (GET /settings/indexers)
func (_ Unimplemented) ListIndexers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create an indexer
// (POST /settings/indexers)
func (_ Unimplemented) CreateIndexer(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete an indexer
// (DELETE /settings/indexers/{id})
func (_ Unimplemented) DeleteIndexer(w http.ResponseWriter, r *http.Request, id ResourceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an indexer
// (PUT /settings/indexers/{id})
func (_ Unimplemented) UpdateIndexer(w http.ResponseWriter, r *http.Request, id ResourceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get detected media tool capabilities
// (GET /system/tools)
func (_ Unimplemented) GetToolStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSession operation middleware
func (siw *ServerInterfaceWrapper) GetSession(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamEvents operation middleware
func (siw *ServerInterfaceWrapper) StreamEvents(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamEvents(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDownloadClients operation middleware
func (siw *ServerInterfaceWrapper) ListDownloadClients(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDownloadClients(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDownloadClient operation middleware
func (siw *ServerInterfaceWrapper) CreateDownloadClient(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDownloadClient(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDownloadClient operation middleware
func (siw *ServerInterfaceWrapper) DeleteDownloadClient(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ResourceId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDownloadClient(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateDownloadClient operation middleware
func (siw *ServerInterfaceWrapper) UpdateDownloadClient(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ResourceId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateDownloadClient(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListIndexers operation middleware
func (siw *ServerInterfaceWrapper) ListIndexers(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListIndexers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateIndexer operation middleware
func (siw *ServerInterfaceWrapper) CreateIndexer(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateIndexer(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteIndexer operation middleware
func (siw *ServerInterfaceWrapper) DeleteIndexer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ResourceId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteIndexer(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateIndexer operation middleware
func (siw *ServerInterfaceWrapper) UpdateIndexer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ResourceId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateIndexer(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetToolStatus operation middleware
func (siw *ServerInterfaceWrapper) GetToolStatus(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetToolStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/session", wrapper.GetSession)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/events", wrapper.StreamEvents)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/settings/download-clients", wrapper.ListDownloadClients)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/settings/download-clients", wrapper.CreateDownloadClient)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/settings/download-clients/{id}", wrapper.DeleteDownloadClient)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/settings/download-clients/{id}", wrapper.UpdateDownloadClient)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/settings/indexers", wrapper.ListIndexers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/settings/indexers", wrapper.CreateIndexer)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/settings/indexers/{id}", wrapper.DeleteIndexer)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/settings/indexers/{id}", wrapper.UpdateIndexer)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/system/tools", wrapper.GetToolStatus)
	})

	return r
}
