package custom

import (
	alpharatio "media-manager/internal/indexers/custom/alpharatio"
	anidex "media-manager/internal/indexers/custom/anidex"
	anidub "media-manager/internal/indexers/custom/anidub"
	animebytes "media-manager/internal/indexers/custom/animebytes"
	animedia "media-manager/internal/indexers/custom/animedia"
	animez "media-manager/internal/indexers/custom/animez"
	avistaz "media-manager/internal/indexers/custom/avistaz"
	bakabt "media-manager/internal/indexers/custom/bakabt"
	beyondhd "media-manager/internal/indexers/custom/beyondhd"
	binsearch "media-manager/internal/indexers/custom/binsearch"
	bithdtv "media-manager/internal/indexers/custom/bithdtv"
	broadcasthenet "media-manager/internal/indexers/custom/broadcasthenet"
	brokenstones "media-manager/internal/indexers/custom/brokenstones"
	cgpeers "media-manager/internal/indexers/custom/cgpeers"
	cinemaz "media-manager/internal/indexers/custom/cinemaz"
	dicmusic "media-manager/internal/indexers/custom/dicmusic"
	exoticaz "media-manager/internal/indexers/custom/exoticaz"
	filelist "media-manager/internal/indexers/custom/filelist"
	funfile "media-manager/internal/indexers/custom/funfile"
	gazelle "media-manager/internal/indexers/custom/gazelle"
	gazellegames "media-manager/internal/indexers/custom/gazellegames"
	greatposterwall "media-manager/internal/indexers/custom/greatposterwall"
	hdbits "media-manager/internal/indexers/custom/hdbits"
	hdspace "media-manager/internal/indexers/custom/hdspace"
	hdtorrents "media-manager/internal/indexers/custom/hdtorrents"
	headphones "media-manager/internal/indexers/custom/headphones"
	immortalseed "media-manager/internal/indexers/custom/immortalseed"
	iptorrents "media-manager/internal/indexers/custom/iptorrents"
	knaben "media-manager/internal/indexers/custom/knaben"
	libble "media-manager/internal/indexers/custom/libble"
	mteamtp "media-manager/internal/indexers/custom/mteamtp"
	myanonamouse "media-manager/internal/indexers/custom/myanonamouse"
	nebulance "media-manager/internal/indexers/custom/nebulance"
	norbits "media-manager/internal/indexers/custom/norbits"
	nzbindex "media-manager/internal/indexers/custom/nzbindex"
	orpheus "media-manager/internal/indexers/custom/orpheus"
	passthepopcorn "media-manager/internal/indexers/custom/passthepopcorn"
	pixelhd "media-manager/internal/indexers/custom/pixelhd"
	pornolab "media-manager/internal/indexers/custom/pornolab"
	pretome "media-manager/internal/indexers/custom/pretome"
	privatehd "media-manager/internal/indexers/custom/privatehd"
	rarbg "media-manager/internal/indexers/custom/rarbg"
	redacted "media-manager/internal/indexers/custom/redacted"
	retroflix "media-manager/internal/indexers/custom/retroflix"
	revolutiontt "media-manager/internal/indexers/custom/revolutiontt"
	rutracker "media-manager/internal/indexers/custom/rutracker"
	scenehd "media-manager/internal/indexers/custom/scenehd"
	scenetime "media-manager/internal/indexers/custom/scenetime"
	secretcinema "media-manager/internal/indexers/custom/secretcinema"
	shazbat "media-manager/internal/indexers/custom/shazbat"
	shizaproject "media-manager/internal/indexers/custom/shizaproject"
	speedapp "media-manager/internal/indexers/custom/speedapp"
	speedcd "media-manager/internal/indexers/custom/speedcd"
	subsplease "media-manager/internal/indexers/custom/subsplease"
	toloka "media-manager/internal/indexers/custom/toloka"
	torrentbytes "media-manager/internal/indexers/custom/torrentbytes"
	torrentday "media-manager/internal/indexers/custom/torrentday"
	torrentpotato "media-manager/internal/indexers/custom/torrentpotato"
	torrentrss "media-manager/internal/indexers/custom/torrentrss"
	torrentscsv "media-manager/internal/indexers/custom/torrentscsv"
	torrentsyndikat "media-manager/internal/indexers/custom/torrentsyndikat"
	uniotaku "media-manager/internal/indexers/custom/uniotaku"
	unit3d "media-manager/internal/indexers/custom/unit3d"
	xspeeds "media-manager/internal/indexers/custom/xspeeds"
	xthor "media-manager/internal/indexers/custom/xthor"
	zonaq "media-manager/internal/indexers/custom/zonaq"
	"media-manager/internal/indexers/engine"
)

func registerProwlarrCustomEngines(registry *Registry, client engine.HTTPDoer) {
	registry.Register("AlphaRatio", alpharatio.New(client))
	registry.Register("Anidex", anidex.New(client))
	registry.Register("Anidub", anidub.New(client))
	registry.Register("AnimeBytes", animebytes.New(client))
	registry.Register("Animedia", animedia.New(client))
	registry.Register("AnimeZ", animez.New(client))
	registry.Register("AvistaZ", avistaz.New(client))
	registry.Register("BakaBT", bakabt.New(client))
	registry.Register("BeyondHD", beyondhd.New(client))
	registry.Register("BinSearch", binsearch.New(client))
	registry.Register("BitHDTV", bithdtv.New(client))
	registry.Register("BroadcastheNet", broadcasthenet.New(client))
	registry.Register("BrokenStones", brokenstones.New(client))
	registry.Register("CGPeers", cgpeers.New(client))
	registry.Register("CinemaZ", cinemaz.New(client))
	registry.Register("DICMusic", dicmusic.New(client))
	registry.Register("ExoticaZ", exoticaz.New(client))
	registry.Register("FileList", filelist.New(client))
	registry.Register("FunFile", funfile.New(client))
	registry.Register("Gazelle", gazelle.New(client))
	registry.Register("GazelleGames", gazellegames.New(client))
	registry.Register("GreatPosterWall", greatposterwall.New(client))
	registry.Register("HDBits", hdbits.New(client))
	registry.Register("HDSpace", hdspace.New(client))
	registry.Register("HDTorrents", hdtorrents.New(client))
	registry.Register("Headphones", headphones.New(client))
	registry.Register("ImmortalSeed", immortalseed.New(client))
	registry.Register("IPTorrents", iptorrents.New(client))
	registry.Register("Knaben", knaben.New(client))
	registry.Register("Libble", libble.New(client))
	registry.Register("MTeamTp", mteamtp.New(client))
	registry.Register("MyAnonamouse", myanonamouse.New(client))
	registry.Register("Nebulance", nebulance.New(client))
	registry.Register("NorBits", norbits.New(client))
	registry.Register("NzbIndex", nzbindex.New(client))
	registry.Register("Orpheus", orpheus.New(client))
	registry.Register("PassThePopcorn", passthepopcorn.New(client))
	registry.Register("PixelHD", pixelhd.New(client))
	registry.Register("PornoLab", pornolab.New(client))
	registry.Register("PreToMe", pretome.New(client))
	registry.Register("PrivateHD", privatehd.New(client))
	registry.Register("Rarbg", rarbg.New(client))
	registry.Register("Redacted", redacted.New(client))
	registry.Register("RetroFlix", retroflix.New(client))
	registry.Register("RevolutionTT", revolutiontt.New(client))
	registry.Register("RuTracker", rutracker.New(client))
	registry.Register("SceneHD", scenehd.New(client))
	registry.Register("SceneTime", scenetime.New(client))
	registry.Register("SecretCinema", secretcinema.New(client))
	registry.Register("Shazbat", shazbat.New(client))
	registry.Register("Shizaproject", shizaproject.New(client))
	registry.Register("SpeedApp", speedapp.New(client))
	registry.Register("SpeedCD", speedcd.New(client))
	registry.Register("SubsPlease", subsplease.New(client))
	registry.Register("Toloka", toloka.New(client))
	registry.Register("TorrentBytes", torrentbytes.New(client))
	registry.Register("TorrentDay", torrentday.New(client))
	registry.Register("TorrentPotato", torrentpotato.New(client))
	registry.Register("TorrentRss", torrentrss.New(client))
	registry.Register("TorrentsCSV", torrentscsv.New(client))
	registry.Register("TorrentSyndikat", torrentsyndikat.New(client))
	registry.Register("Uniotaku", uniotaku.New(client))
	registry.Register("UNIT3D", unit3d.New(client))
	registry.Register("XSpeeds", xspeeds.New(client))
	registry.Register("Xthor", xthor.New(client))
	registry.Register("ZonaQ", zonaq.New(client))
}
