import { vi } from 'vitest';
import type { AppShellController } from '$lib/features/app/appShellContext';
import { emptyMetadataCache } from '$lib/settings/api';
import {
	emptyCustomFormatForm,
	emptyDownloadClientForm,
	emptyIndexerForm,
	emptyLanguageForm,
	emptyLibraryFolderForm,
	emptyPathMappingForm
} from '$lib/settings/forms';
import {
	emptyIndexerSearch,
	managedUser,
	metadataProvider,
	tag,
	userForm,
	userSummary
} from './appShellTestValues';

export function createAppShell(overrides: Partial<AppShellController> = {}): AppShellController {
	return {
		isAdmin: true,
		currentUser: userSummary(),
		users: [managedUser()],
		userForm: userForm(),
		savingUser: false,
		saveUser: vi.fn(),
		cancelUser: vi.fn(),
		editUser: vi.fn(),
		deleteUser: vi.fn(),
		tags: [tag()],
		tagForm: { name: '' },
		savingTag: false,
		deletingTagId: undefined,
		saveTag: vi.fn(),
		cancelTag: vi.fn(),
		editTag: vi.fn(),
		deleteTag: vi.fn(),
		customFormats: [],
		customFormatForm: emptyCustomFormatForm(),
		savingCustomFormat: false,
		deletingCustomFormatId: undefined,
		saveCustomFormat: vi.fn(),
		importCustomFormat: vi.fn(),
		cancelCustomFormat: vi.fn(),
		editCustomFormat: vi.fn(),
		deleteCustomFormat: vi.fn(),
		downloadClients: [],
		downloadForm: emptyDownloadClientForm(),
		savingDownloadClient: false,
		saveDownloadClient: vi.fn(),
		testDownloadClientConfig: vi.fn(),
		cancelDownloadClient: vi.fn(),
		editDownloadClient: vi.fn(),
		deleteDownloadClient: vi.fn(),
		indexers: [],
		indexerSearch: emptyIndexerSearch(),
		indexerForm: emptyIndexerForm(),
		savingIndexer: false,
		clearingIndexerSearchCache: false,
		savingIndexerSearchSettings: false,
		testingIndexerId: undefined,
		indexerTests: {},
		saveIndexer: vi.fn(),
		cancelIndexer: vi.fn(),
		editIndexer: vi.fn(),
		deleteIndexer: vi.fn(),
		testIndexer: vi.fn(),
		clearIndexerSearchCache: vi.fn(),
		saveIndexerSearchSettings: vi.fn(),
		metadataProviders: [metadataProvider()],
		saveMetadataProvider: vi.fn(),
		testMetadataProvider: vi.fn(),
		testingMetadataProviderId: undefined,
		savingMetadataProviderId: undefined,
		metadataProviderTests: {},
		metadataCache: emptyMetadataCache(),
		loadingMetadataCache: false,
		clearingMetadataCache: false,
		clearMetadataCache: vi.fn(),
		clearMetadataCachePattern: vi.fn(),
		deleteMetadataCacheEntry: vi.fn(),
		clearMetadataSearchHistory: vi.fn(),
		loadMoreMetadataCache: vi.fn(),
		loadMoreMetadataSearchHistory: vi.fn(),
		advancedSearchGroups: [],
		searchingAdvanced: false,
		advancedSearch: vi.fn(),
		addMedia: vi.fn(),
		discoverSection: undefined,
		discoverSections: [],
		discoverBlacklist: [],
		mediaItems: [],
		mediaRequests: [],
		libraryFolders: [],
		libraryFolderForm: emptyLibraryFolderForm(),
		pathMappings: [],
		pathMappingForm: emptyPathMappingForm(),
		libraryScansByFolder: {},
		openLibraryFolderId: undefined,
		savingLibraryFolder: false,
		scanningLibraryFolderId: undefined,
		savingPathMapping: false,
		deletingPathMappingId: undefined,
		saveLibraryFolder: vi.fn(),
		scanLibraryFolder: vi.fn(),
		deleteLibraryFolder: vi.fn(),
		savePathMapping: vi.fn(),
		deletePathMapping: vi.fn(),
		searchLibraryMatch: vi.fn(),
		importLibraryScanRows: vi.fn(),
		languages: [],
		languageForm: emptyLanguageForm(),
		savingLanguage: false,
		deletingLanguageCode: undefined,
		saveLanguage: vi.fn(),
		cancelLanguage: vi.fn(),
		editLanguage: vi.fn(),
		deleteLanguage: vi.fn(),
		mediaProfiles: [],
		deletingMediaProfileId: undefined,
		deleteMediaProfile: vi.fn(),
		activities: [],
		loadingDiscover: false,
		loadingBlacklist: false,
		loadingMediaItems: false,
		loadingActivity: false,
		loadingDiscoverSection: false,
		loadingMoreDiscoverSection: false,
		discoverSectionHasMore: false,
		addingKey: undefined,
		blacklistingKey: undefined,
		removingBlacklistId: undefined,
		approvingRequestId: undefined,
		searchingItemId: undefined,
		refreshingMetadataItemId: undefined,
		savingMediaItemOptionsId: undefined,
		grabbingKey: undefined,
		deletingMediaItemId: undefined,
		cancellingActivityId: undefined,
		deletingActivityId: undefined,
		onSearch: vi.fn(),
		blacklistDiscoverMedia: vi.fn(),
		removeDiscoverBlacklistItem: vi.fn(),
		approveMediaRequest: vi.fn(),
		findReleases: vi.fn(),
		autoSearchMedia: vi.fn(),
		refreshMediaMetadata: vi.fn(),
		saveMediaItemOptions: vi.fn(),
		deleteMediaFile: vi.fn(),
		deleteMediaItem: vi.fn(),
		grabRelease: vi.fn(),
		loadDownloadActivity: vi.fn(),
		cancelActivity: vi.fn(),
		deleteActivity: vi.fn(),
		loadMoreDiscoverSection: vi.fn(),
		mediaCollection: undefined,
		loadingMediaCollection: false,
		metadataDetail: undefined,
		loadingMetadataDetail: false,
		...overrides
	} as unknown as AppShellController;
}
