//go:build subtitlecatalog

package main

import "media-manager/internal/subtitles/catalog"

var subtitleProviderCatalogDefinitionsAPI = []subtitleProviderDefinition{
	{Key: "assrt", DisplayName: "Assrt", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "betaseries", DisplayName: "Betaseries", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "gestdown", DisplayName: "Gestdown", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "jimaku", DisplayName: "Jimaku", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "regielive", DisplayName: "Regielive", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "subdl", DisplayName: "Subdl", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{Archive: true}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "subsource", DisplayName: " Subsource", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{Archive: true}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "subsarr", DisplayName: " Subsarr", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "subsro", DisplayName: " Subsro", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "subtis", DisplayName: "Subtis", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "subx", DisplayName: "Subx", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
}
