//go:build subtitlecatalog

package main

import "media-manager/internal/subtitles/catalog"

var subtitleProviderCatalogDefinitionsAuth = []subtitleProviderDefinition{
	{Key: "addic7ed", DisplayName: "Addic7Ed", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{Captcha: true}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "avistaz", DisplayName: "Avistaz", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "cinemaz", DisplayName: "Cinemaz", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "hdbits", DisplayName: "HDBits", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "karagarga", DisplayName: "Karagarga", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "ktuvit", DisplayName: "Ktuvit", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{Captcha: true}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "legendasdivx", DisplayName: "Legendasdivx", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "legendasnet", DisplayName: "Legendasnet", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{Captcha: true}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "napisy24", DisplayName: "Napisy24", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "pipocas", DisplayName: "Pipocas", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "subs4series", DisplayName: "Subs4Series", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "subscenter", DisplayName: " Subscenter", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{Captcha: true}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "titlovi", DisplayName: "Titlovi", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "titulky", DisplayName: "Titulky", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "turkcealtyaziorg", DisplayName: "Turkcealtyaziorg", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "xsubs", DisplayName: "X Subs", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "zimuku", DisplayName: "Zimuku", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{Archive: true}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
}
