//go:build subtitlecatalog

package main

import "media-manager/internal/subtitles/catalog"

var subtitleProviderCatalogDefinitionsPublic = []subtitleProviderDefinition{
	{Key: "animekalesi", DisplayName: "Animekalesi", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeSupported, RuntimeMessage: "Native public HTML adapter implemented.", MediaTypes: []string{"serie"}, Dependencies: catalog.Dependencies{Archive: true}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{"animekalesi.com"}, AllowedDownloadHosts: []string{"animekalesi.com"}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "animesubinfo", DisplayName: "Animesubinfo", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeSupported, RuntimeMessage: "Native public HTML adapter implemented.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{Archive: true}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{"animesub.info"}, AllowedDownloadHosts: []string{"animesub.info"}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "bayflix", DisplayName: "Bayflix", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeSupported, RuntimeMessage: "Native public HTML adapter implemented.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{"bayflix.sb"}, AllowedDownloadHosts: []string{"bayflix.sb"}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "greeksubs", DisplayName: "Greek Subs", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeSupported, RuntimeMessage: "Native public HTML adapter implemented.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{"greeksubs.net"}, AllowedDownloadHosts: []string{"greeksubs.net"}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "greeksubtitles", DisplayName: "Greek Subtitles", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeSupported, RuntimeMessage: "Native public HTML adapter implemented.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{"gr.greek-subtitles.com", "greeksubtitles.info"}, AllowedDownloadHosts: []string{"gr.greek-subtitles.com", "greeksubtitles.info"}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "hosszupuska", DisplayName: "Hosszupuska", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeSupported, RuntimeMessage: "Native public HTML adapter implemented.", MediaTypes: []string{"serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{"hosszupuskasub.com"}, AllowedDownloadHosts: []string{"hosszupuskasub.com"}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "nekur", DisplayName: "Nekur", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeSupported, RuntimeMessage: "Native public HTML adapter implemented.", MediaTypes: []string{"movie"}, Dependencies: catalog.Dependencies{Archive: true}, Warning: "Plaintext HTTP upstream.", OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{"subtitri.nekur.net"}, AllowedDownloadHosts: []string{"subtitri.nekur.net"}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "prijevodionline", DisplayName: "Prijevodionline", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeSupported, RuntimeMessage: "Native public HTML adapter implemented.", MediaTypes: []string{"serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{"prijevodi-online.org"}, AllowedDownloadHosts: []string{"prijevodi-online.org"}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "soustitreseu", DisplayName: "Sous-titres.eu", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeSupported, RuntimeMessage: "Native public HTML adapter implemented.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{Archive: true}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{"sous-titres.eu"}, AllowedDownloadHosts: []string{"sous-titres.eu"}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "subclub", DisplayName: "Subclub", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeSupported, RuntimeMessage: "Native public HTML adapter implemented.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{"subclub.eu"}, AllowedDownloadHosts: []string{"subclub.eu"}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "subf2m", DisplayName: "Subf2M", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeSupported, RuntimeMessage: "Native public HTML adapter implemented.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{"subf2m.co"}, AllowedDownloadHosts: []string{"subf2m.co"}, AllowLocalHosts: false}, Fields: []catalog.Field{{Key: "verifySsl", Label: "Verify SSL", Type: catalog.FieldSwitch, Persisted: true}, {Key: "userAgent", Label: "User-Agent", Type: catalog.FieldText, Persisted: true}}},
	{Key: "subs4free", DisplayName: "Subs4Free", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeSupported, RuntimeMessage: "Native public HTML adapter implemented.", MediaTypes: []string{"movie"}, Dependencies: catalog.Dependencies{Archive: true}, Warning: "Bazarr marks this upstream as broken; runtime returns provider_broken_upstream on anti-block/layout failures.", OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{"subs4free.info", "images.subs4free.info", "subs4series.com"}, AllowedDownloadHosts: []string{"subs4free.info", "images.subs4free.info", "subs4series.com"}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "subssabbz", DisplayName: "Subs.sab.bz", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeSupported, RuntimeMessage: "Native public HTML adapter implemented.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, Warning: "Plaintext HTTP upstream.", OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{"subs.sab.bz"}, AllowedDownloadHosts: []string{"subs.sab.bz"}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "subsunacs", DisplayName: "Subsunacs", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeSupported, RuntimeMessage: "Native public HTML adapter implemented.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{Archive: true}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{"subsunacs.net"}, AllowedDownloadHosts: []string{"subsunacs.net"}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "subsynchro", DisplayName: "Subsynchro", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeSupported, RuntimeMessage: "Native public HTML adapter implemented.", MediaTypes: []string{"movie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{"subsynchro.com"}, AllowedDownloadHosts: []string{"subsynchro.com"}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "subtitrarinoi", DisplayName: "Subtitrari Noi", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeSupported, RuntimeMessage: "Native public HTML adapter implemented.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{Archive: true}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{"subtitrari-noi.ro"}, AllowedDownloadHosts: []string{"subtitrari-noi.ro"}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "subtitriid", DisplayName: "Subtitriid", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeSupported, RuntimeMessage: "Native public HTML adapter implemented.", MediaTypes: []string{"movie"}, Dependencies: catalog.Dependencies{Archive: true}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{"subtitri.do.am"}, AllowedDownloadHosts: []string{"subtitri.do.am"}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "subtitulamostv", DisplayName: "Subtitulamos.tv", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeSupported, RuntimeMessage: "Native public HTML adapter implemented.", MediaTypes: []string{"serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{"subtitulamos.tv"}, AllowedDownloadHosts: []string{"subtitulamos.tv"}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "supersubtitles", DisplayName: "Super Subtitles", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeSupported, RuntimeMessage: "Native public HTML adapter implemented.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, Warning: "Bazarr forces this provider off when upstream blocks or layout drifts.", OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{"feliratok.eu"}, AllowedDownloadHosts: []string{"feliratok.eu"}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "titrari", DisplayName: "Titrari", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeSupported, RuntimeMessage: "Native public HTML adapter implemented.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{Archive: true}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{"titrari.ro"}, AllowedDownloadHosts: []string{"titrari.ro"}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "tvsubtitles", DisplayName: "TVsubtitles", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeSupported, RuntimeMessage: "Native public HTML adapter implemented.", MediaTypes: []string{"serie"}, Dependencies: catalog.Dependencies{}, Warning: "Bazarr marks this upstream unstable; runtime reports broken-upstream for unrecognized layouts.", OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{"tvsubtitles.net"}, AllowedDownloadHosts: []string{"tvsubtitles.net"}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "vladoonmooo", DisplayName: "Vladoonmooo", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeSupported, RuntimeMessage: "Native public HTML adapter implemented.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{Archive: true}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{"vladoon.mooo.com"}, AllowedDownloadHosts: []string{"vladoon.mooo.com"}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "wizdom", DisplayName: "Wizdom", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeSupported, RuntimeMessage: "Native public HTML adapter implemented.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{"wizdom.xyz"}, AllowedDownloadHosts: []string{"wizdom.xyz"}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "yavkanet", DisplayName: "Yavka.net", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeSupported, RuntimeMessage: "Native public HTML adapter implemented.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{"yavka.net"}, AllowedDownloadHosts: []string{"yavka.net"}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "yifysubtitles", DisplayName: "YIFY Subtitles", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeSupported, RuntimeMessage: "Native public HTML adapter implemented.", MediaTypes: []string{"movie"}, Dependencies: catalog.Dependencies{Archive: true}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{"yifysubtitles.ch"}, AllowedDownloadHosts: []string{"yifysubtitles.ch"}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
}
