//go:build subtitlecatalog

package main

import "media-manager/internal/subtitles/catalog"

var subtitleProviderCatalogDefinitionsPublic = []subtitleProviderDefinition{
	{Key: "animekalesi", DisplayName: "Animekalesi", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "animesubinfo", DisplayName: "Animesubinfo", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "bayflix", DisplayName: "Bayflix", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "greeksubs", DisplayName: "Greek Subs", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "greeksubtitles", DisplayName: "Greek Subtitles", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "hosszupuska", DisplayName: "Hosszupuska", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "nekur", DisplayName: "Nekur", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "prijevodionline", DisplayName: "Prijevodionline", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "soustitreseu", DisplayName: "Soustitreseu", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "subclub", DisplayName: "Subclub", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "subf2m", DisplayName: "Subf2M", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "subs4free", DisplayName: "Subs4Free", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "subssabbz", DisplayName: " Subssabbz", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "subsunacs", DisplayName: " Subsunacs", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "subsynchro", DisplayName: " Subsynchro", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "subtitrarinoi", DisplayName: "Subtitrarinoi", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "subtitriid", DisplayName: "Subtitriid", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "subtitulamostv", DisplayName: "Subtitulamostv", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "supersubtitles", DisplayName: "Super Subtitles", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "titrari", DisplayName: "Titrari", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "tvsubtitles", DisplayName: "TVsubtitles", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "vladoonmooo", DisplayName: "Vladoonmooo", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "wizdom", DisplayName: "Wizdom", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "yavkanet", DisplayName: "Yavkanet", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
	{Key: "yifysubtitles", DisplayName: "YIFY Subtitles", ProvenanceCommit: bazarrProviderListCommit, RuntimeStatus: catalog.RuntimeCatalogOnly, RuntimeMessage: "Catalog entry only; runtime support is not implemented yet.", MediaTypes: []string{"movie", "serie"}, Dependencies: catalog.Dependencies{Archive: true}, OutboundPolicy: catalog.OutboundPolicy{AllowedBaseHosts: []string{}, AllowedDownloadHosts: []string{}, AllowLocalHosts: false}, Fields: []catalog.Field{}},
}
