-- name: ListIndexers :many
select id,
    definition_id,
    name,
    type,
    implementation,
    implementation_name,
    protocol,
    privacy,
    language,
    encoding,
    description,
    indexer_urls,
    legacy_urls,
    base_url,
    api_key,
    categories,
    media_type_scopes,
    tag_scopes,
    fields,
    capabilities,
    redirect,
    app_profile_id,
    minimum_seeders,
    seed_ratio,
    seed_time,
    pack_seed_time,
    prefer_magnet_url,
    supports_rss,
    supports_search,
    supports_redirect,
    supports_pagination,
    enabled,
    priority,
    health_status,
    last_query_at,
    last_success_at,
    last_failure_at,
    next_check_at,
    last_status_code,
    last_error,
    failure_count,
    rss_marker_published_at,
    rss_marker_guid,
    rss_marker_download_url,
    created_at,
    updated_at
from app.indexers
order by priority asc, name asc;

-- name: ListEnabledIndexers :many
select id,
    definition_id,
    name,
    type,
    implementation,
    implementation_name,
    protocol,
    privacy,
    language,
    encoding,
    description,
    indexer_urls,
    legacy_urls,
    base_url,
    api_key,
    categories,
    media_type_scopes,
    tag_scopes,
    fields,
    capabilities,
    redirect,
    app_profile_id,
    minimum_seeders,
    seed_ratio,
    seed_time,
    pack_seed_time,
    prefer_magnet_url,
    supports_rss,
    supports_search,
    supports_redirect,
    supports_pagination,
    enabled,
    priority,
    health_status,
    last_query_at,
    last_success_at,
    last_failure_at,
    next_check_at,
    last_status_code,
    last_error,
    failure_count,
    rss_marker_published_at,
    rss_marker_guid,
    rss_marker_download_url,
    created_at,
    updated_at
from app.indexers
where enabled = true
    and health_status <> 'disabled'
    and (next_check_at is null or next_check_at <= now())
order by priority asc, name asc;

-- name: GetIndexer :one
select id,
    definition_id,
    name,
    type,
    implementation,
    implementation_name,
    protocol,
    privacy,
    language,
    encoding,
    description,
    indexer_urls,
    legacy_urls,
    base_url,
    api_key,
    categories,
    media_type_scopes,
    tag_scopes,
    fields,
    capabilities,
    redirect,
    app_profile_id,
    minimum_seeders,
    seed_ratio,
    seed_time,
    pack_seed_time,
    prefer_magnet_url,
    supports_rss,
    supports_search,
    supports_redirect,
    supports_pagination,
    enabled,
    priority,
    health_status,
    last_query_at,
    last_success_at,
    last_failure_at,
    next_check_at,
    last_status_code,
    last_error,
    failure_count,
    rss_marker_published_at,
    rss_marker_guid,
    rss_marker_download_url,
    created_at,
    updated_at
from app.indexers
where id = $1;

-- name: CreateIndexer :one
insert into app.indexers (
    id,
    definition_id,
    name,
    implementation,
    implementation_name,
    protocol,
    privacy,
    language,
    encoding,
    description,
    indexer_urls,
    legacy_urls,
    base_url,
    api_key,
    categories,
    media_type_scopes,
    tag_scopes,
    fields,
    capabilities,
    redirect,
    app_profile_id,
    minimum_seeders,
    seed_ratio,
    seed_time,
    pack_seed_time,
    prefer_magnet_url,
    supports_rss,
    supports_search,
    supports_redirect,
    supports_pagination,
    enabled,
    priority
)
values (
    sqlc.arg(id),
    sqlc.arg(definition_id),
    sqlc.arg(name),
    sqlc.arg(implementation),
    sqlc.arg(implementation_name),
    sqlc.arg(protocol),
    sqlc.arg(privacy),
    sqlc.arg(language),
    sqlc.narg(encoding),
    sqlc.narg(description),
    sqlc.arg(indexer_urls),
    sqlc.arg(legacy_urls),
    sqlc.arg(base_url),
    sqlc.narg(api_key),
    sqlc.arg(categories),
    sqlc.arg(media_type_scopes),
    sqlc.arg(tag_scopes),
    sqlc.arg(fields),
    sqlc.arg(capabilities),
    sqlc.arg(redirect),
    sqlc.arg(app_profile_id),
    sqlc.narg(minimum_seeders),
    sqlc.narg(seed_ratio),
    sqlc.narg(seed_time),
    sqlc.narg(pack_seed_time),
    sqlc.arg(prefer_magnet_url),
    sqlc.arg(supports_rss),
    sqlc.arg(supports_search),
    sqlc.arg(supports_redirect),
    sqlc.arg(supports_pagination),
    sqlc.arg(enabled),
    sqlc.arg(priority)
)
returning id,
    definition_id,
    name,
    type,
    implementation,
    implementation_name,
    protocol,
    privacy,
    language,
    encoding,
    description,
    indexer_urls,
    legacy_urls,
    base_url,
    api_key,
    categories,
    media_type_scopes,
    tag_scopes,
    fields,
    capabilities,
    redirect,
    app_profile_id,
    minimum_seeders,
    seed_ratio,
    seed_time,
    pack_seed_time,
    prefer_magnet_url,
    supports_rss,
    supports_search,
    supports_redirect,
    supports_pagination,
    enabled,
    priority,
    health_status,
    last_query_at,
    last_success_at,
    last_failure_at,
    next_check_at,
    last_status_code,
    last_error,
    failure_count,
    rss_marker_published_at,
    rss_marker_guid,
    rss_marker_download_url,
    created_at,
    updated_at;

-- name: UpdateIndexer :one
update app.indexers
set definition_id = sqlc.arg(definition_id),
    name = sqlc.arg(name),
    implementation = sqlc.arg(implementation),
    implementation_name = sqlc.arg(implementation_name),
    protocol = sqlc.arg(protocol),
    privacy = sqlc.arg(privacy),
    language = sqlc.arg(language),
    encoding = sqlc.narg(encoding),
    description = sqlc.narg(description),
    indexer_urls = sqlc.arg(indexer_urls),
    legacy_urls = sqlc.arg(legacy_urls),
    base_url = sqlc.arg(base_url),
    api_key = sqlc.narg(api_key),
    categories = sqlc.arg(categories),
    media_type_scopes = sqlc.arg(media_type_scopes),
    tag_scopes = sqlc.arg(tag_scopes),
    fields = sqlc.arg(fields),
    capabilities = sqlc.arg(capabilities),
    redirect = sqlc.arg(redirect),
    app_profile_id = sqlc.arg(app_profile_id),
    minimum_seeders = sqlc.narg(minimum_seeders),
    seed_ratio = sqlc.narg(seed_ratio),
    seed_time = sqlc.narg(seed_time),
    pack_seed_time = sqlc.narg(pack_seed_time),
    prefer_magnet_url = sqlc.arg(prefer_magnet_url),
    supports_rss = sqlc.arg(supports_rss),
    supports_search = sqlc.arg(supports_search),
    supports_redirect = sqlc.arg(supports_redirect),
    supports_pagination = sqlc.arg(supports_pagination),
    enabled = sqlc.arg(enabled),
    priority = sqlc.arg(priority),
    health_status = 'healthy',
    last_query_at = null,
    last_success_at = null,
    last_failure_at = null,
    next_check_at = null,
    last_status_code = null,
    last_error = null,
    failure_count = 0,
    updated_at = now()
where id = sqlc.arg(id)
returning id,
    definition_id,
    name,
    type,
    implementation,
    implementation_name,
    protocol,
    privacy,
    language,
    encoding,
    description,
    indexer_urls,
    legacy_urls,
    base_url,
    api_key,
    categories,
    media_type_scopes,
    tag_scopes,
    fields,
    capabilities,
    redirect,
    app_profile_id,
    minimum_seeders,
    seed_ratio,
    seed_time,
    pack_seed_time,
    prefer_magnet_url,
    supports_rss,
    supports_search,
    supports_redirect,
    supports_pagination,
    enabled,
    priority,
    health_status,
    last_query_at,
    last_success_at,
    last_failure_at,
    next_check_at,
    last_status_code,
    last_error,
    failure_count,
    rss_marker_published_at,
    rss_marker_guid,
    rss_marker_download_url,
    created_at,
    updated_at;

-- name: RecordIndexerSuccess :one
update app.indexers
set health_status = 'healthy',
    last_query_at = now(),
    last_success_at = now(),
    last_failure_at = null,
    next_check_at = null,
    last_status_code = null,
    last_error = null,
    failure_count = 0,
    updated_at = now()
where id = $1
returning id,
    definition_id,
    name,
    type,
    implementation,
    implementation_name,
    protocol,
    privacy,
    language,
    encoding,
    description,
    indexer_urls,
    legacy_urls,
    base_url,
    api_key,
    categories,
    media_type_scopes,
    tag_scopes,
    fields,
    capabilities,
    redirect,
    app_profile_id,
    minimum_seeders,
    seed_ratio,
    seed_time,
    pack_seed_time,
    prefer_magnet_url,
    supports_rss,
    supports_search,
    supports_redirect,
    supports_pagination,
    enabled,
    priority,
    health_status,
    last_query_at,
    last_success_at,
    last_failure_at,
    next_check_at,
    last_status_code,
    last_error,
    failure_count,
    rss_marker_published_at,
    rss_marker_guid,
    rss_marker_download_url,
    created_at,
    updated_at;

-- name: RecordIndexerFailure :one
update app.indexers
set health_status = case
        when sqlc.arg(permanent)::boolean then 'disabled'
        when failure_count >= 5 then 'disabled'
        else 'temporary_disabled'
    end,
    last_query_at = now(),
    last_failure_at = now(),
    last_status_code = sqlc.narg(status_code),
    last_error = sqlc.arg(message)::text,
    failure_count = failure_count + 1,
    next_check_at = case
        when sqlc.arg(permanent)::boolean then null
        when failure_count >= 5 then null
        when sqlc.narg(retry_until)::timestamptz is not null then sqlc.narg(retry_until)::timestamptz
        when failure_count = 0 then now() + interval '1 minute'
        when failure_count = 1 then now() + interval '5 minutes'
        when failure_count = 2 then now() + interval '15 minutes'
        when failure_count = 3 then now() + interval '30 minutes'
        when failure_count = 4 then now() + interval '1 hour'
        else null
    end,
    updated_at = now()
where id = sqlc.arg(id)
returning id,
    definition_id,
    name,
    type,
    implementation,
    implementation_name,
    protocol,
    privacy,
    language,
    encoding,
    description,
    indexer_urls,
    legacy_urls,
    base_url,
    api_key,
    categories,
    media_type_scopes,
    tag_scopes,
    fields,
    capabilities,
    redirect,
    app_profile_id,
    minimum_seeders,
    seed_ratio,
    seed_time,
    pack_seed_time,
    prefer_magnet_url,
    supports_rss,
    supports_search,
    supports_redirect,
    supports_pagination,
    enabled,
    priority,
    health_status,
    last_query_at,
    last_success_at,
    last_failure_at,
    next_check_at,
    last_status_code,
    last_error,
    failure_count,
    rss_marker_published_at,
    rss_marker_guid,
    rss_marker_download_url,
    created_at,
    updated_at;

-- name: DeleteIndexer :execrows
delete from app.indexers
where id = $1;
